ci: :fire: Remove CD file and improved CI Pipeline file

diff --git a/.github/workflows/CI-CD.yml b/.github/workflows/CI-CD.yml
--- a/.github/workflows/CI-CD.yml
+++ b/.github/workflows/CI-CD.yml
@@ -1,26 +1,52 @@
-name: CD Pipeline
+name: CI/CD Pipeline
 
 on:
-  workflow_run:
-    workflows: ["CI Pipeline"]
-    types:
-      - completed
+  pull_request:
+    branches:
+      - "QA"
+      - "main"
 
 jobs:
-  deploy:
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
+  ci_cd:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Set Target Environment
-        id: set-env
+      - name: Checkout Code
+        uses: actions/checkout@v3
+
+      - name: Login to Docker Hub
+        env:
+          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
+
+      - name: Build and Tag the Docker Image
         run: |
-          if [[ "${{ github.event.workflow_run.outputs.branch }}" == "QA" ]]; then
+          if [[ "${{ github.event.pull_request.base.ref }}" == "QA" ]]; then
+            docker build -t ${{ secrets.DOCKER_USERNAME }}/lb_asg:qa .
+          elif [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
+            docker build -t ${{ secrets.DOCKER_USERNAME }}/lb_asg:prod .
+          else
+            echo "Invalid branch for building Docker image."
+            exit 1
+          fi
+
+      - name: Push the Docker Image
+        run: |
+          if [[ "${{ github.event.pull_request.base.ref }}" == "QA" ]]; then
+            docker push ${{ secrets.DOCKER_USERNAME }}/lb_asg:qa
+          elif [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
+            docker push ${{ secrets.DOCKER_USERNAME }}/lb_asg:prod
+          fi
+
+      - name: Set Target Environment
+        run: |
+          if [[ "${{ github.event.pull_request.base.ref }}" == "QA" ]]; then
             echo "env=QA" >> $GITHUB_ENV
             echo "host=${{ secrets.EC2_HOSTSQA }}" >> $GITHUB_ENV
             echo "key=${{ secrets.EC2_KEYQA }}" >> $GITHUB_ENV
             echo "image_tag=qa" >> $GITHUB_ENV
-          elif [[ "${{ github.event.workflow_run.outputs.branch }}" == "main" ]]; then
+          elif [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
             echo "env=PROD" >> $GITHUB_ENV
             echo "host=${{ secrets.EC2_HOSTPROD }}" >> $GITHUB_ENV
             echo "key=${{ secrets.EC2_KEY }}" >> $GITHUB_ENV
@@ -29,7 +55,6 @@ jobs:
             echo "No valid branch detected for deployment."
             exit 1
           fi
-        shell: bash
 
       - name: Deploy to Target Environment
         uses: appleboy/ssh-action@v1.2.0
